# any language
language: python

services:
  - docker

script:
  - docker -v
  - docker build --no-cache -t sonarsource/sonarqube-scan-action .
  - docker image ls sonarsource/sonarqube-scan-action
  - docker history sonarsource/sonarqube-scan-action
